### ISSUE TITLE
false error with components negation 

### ISSUE THREAD

**Issue by dvirov** [SpyglassMC/Spyglass#1604] opened 2024-09-24 12:10 UTC
item replace block ~ ~ ~ container.16 with minecraft:music_disc_11[!minecraft:jukebox_playable] 1

is valid comman but it mark the "!minecraft:jukebox_playeble" as error 
![image](https://github.com/user-attachments/assets/866bf350-e52e-41f2-ab1d-b6e7a101874e)

**Comment by misode** [comment] 2024-09-24 12:12
Duplicate of #1496

**Closed by misode** 2024-09-24 12:12 UTC
