### ISSUE TITLE
JSON text component does not autocomplete some fields (notably `storage`, `nbt`, `entity`, `block`, `selector`, and `score`)

### ISSUE THREAD

**Issue by beegyfleeg** [SPYGlassMC/SPYGlass#898] opened 2021-07-30 02:37 UTC
Details:

- VSCode 1.58.2 on Windows x64 (it has been this way for a while)
- Problem does not fix after reinstallation, even if the extension is cleared from disc manually
- Subcomponents (like `name` and `objective` of `score`) *do* autocomplete once the components specified above are manually typed in
- Syntax highlighting is performed correctly once the key is typed in (such as highlighting for `selector` and `nbt`)
- **The only issue is that these keys do not show up in autocomplete, but they work in all other aspects.**

How to replicate:

1. Type in the line `tellraw @a {`
2. Press ctrl+space to trigger autocomplete suggestions if necessary (other options should show up)
3. The tags listed in the title do not show up

**Comment by SPGoding** [comment] 2021-07-30 02:39
Duplicate of #832, which will be fixed in the next major release.

**Closed by SPGoding** 2021-07-30 02:39 UTC
Labels: *forwarded
