### ISSUE TITLE
Extension causes file lock.

### ISSUE THREAD

**Issue by Kazii78** [SpyglassMC/Spyglass#1522] opened 2024-07-14 09:53 UTC
OS: WIndows 11
Installed extension: Datapack Helper Plus by Spyglass (v4.1.2) (with syntax-mcfunction (v1.0.0))

Messing around your workspace for a while, causes the extension to hold your files (mostly folders) in a lock.
Renaming, moving (the most common issues) will not go through and end up in an EPERM error after a couple minutes.

I cannot tell the reproduction steps as I have no idea as to what's causing it.
However, I suspect that if you mess around in a folder, add some files, rename, delete, just mess with it,
then try to rename it, it will cause that. I'm unsure.

It might correlate to the whole extension freezing, it breaks syntax highlighting, auto-completion and syntax detection.

This has been going on for past versions and I'm unable to fix it.

![renaming](https://github.com/user-attachments/assets/c5f826d5-aa15-4e5f-8090-d7d02e1f402f)
This will sit here for a couple minutes, then end up in an

![error](https://github.com/user-attachments/assets/63d7d8d3-1e33-4251-b154-0f61dc606a9e)
EPERM error.

Error: EPERM: operation not permitted, rename 'path a' -> 'path b'

I've tried general troubleshooting steps like running VSCode as administrator.
Nothing has worked as of now.

EDIT 1: Reloading VSCode immediately after renaming will allow the rename to go through. Not very practical though.

**Comment by misode** [comment] 2024-07-14 10:19
Duplicate of #1414

**Closed** 2024-07-14 10:19 UTC
