### ISSUE TITLE
Undefined function error in advancements function reward is missing Quick Fix

### ISSUE THREAD

**Issue by NeunEinser** [SPYGlassMC/SPYGlass#866] opened 2021-03-10 13:49 UTC
Using the /function command, there is a quick fix "Create function in same datapack".

That is missing in function rewards from advancements though.

![grafik](https://user-images.githubusercontent.com/12124394/110639248-cb991800-81af-11eb-92ad-8d274d834ce9.png)

**Comment by SPGoding** [comment] 2021-04-07 04:13
Duplicate of #672

**Closed by SPGoding** 2021-04-07 04:13 UTC
Labels: *forwarded
