### ISSUE TITLE
Compound predicates in nbt paths are not verified or auto completed

### ISSUE THREAD

**Issue by NeunEinser** [SpyglassMC/Spyglass#1513] opened 2024-07-10 18:41 UTC
- `execute if data entity @s carriedBlockState{ahhhhhh: true}`
- ❌ No error shows
- `execute if data entity @s Items[{ahhhhhh: true}]`
- ❌ No error shows

**Comment by misode** [comment] 2024-07-10 20:29
Duplicate of #1365

**Closed by misode** 2024-07-10 20:29 UTC
Labels: 🐛 bug, /nbt
