### ISSUE TITLE
Feature Suggestion: Automatically inserting backslashes and indentations in mcfunction files

### ISSUE THREAD

**Issue by Dahesor** [SpyglassMC/Spyglass#1618] opened 2024-10-11 17:58 UTC
It would be nice if a back slash and indentation is automatically inserted if you press enter while your cursor is at the middle of a line, for example:

```
execute if score @s foo matches 1 run (cursor)effect give @s absorption infinite 4 true
```
  ↓↓↓
```
execute if score @s foo matches 1 run\
    (cursor)effect give @s absorption infinite 4 true
```

Also, if possible, open and extend brackets in snbt just like json:

```
data modify storage foo:bar data set value {(curser)}
```
  ↓↓↓
```
data modify storage foo:bar data set value {\
    (curser)\
}
```

I have no idea how difficult this is though. 
Thanks

**Comment by misode** [comment] 2024-10-11 18:08
Does #1170 describe your feature request?

**Comment by Dahesor** [comment] 2024-10-12 12:52
> Does [#1170](https://github.com/SpyglassMC/Spyglass/issues/1170) describe your feature request?

I would say #1170 is a *subset* of this one? What's extra on this is that a slash can be placed not just for brackets but also when you are at the middle of a line (should maybe be configurable). If important discussions are happening there, maybe move this to there as a comment?

**Comment by MulverineX** [comment] 2024-10-16 12:38
Duplicate of #1170

**Closed by MulverineX** 2024-10-16 12:38 UTC
