### ISSUE TITLE
"Expected a list" error at list

### ISSUE THREAD

**Issue by Bill2439** [SpyglassMC/Spyglass#1500] opened 2024-07-09 06:58 UTC
Throwing "Expected a list" error on this: [I;0,0,0], which I am using to modify the Motion value of entities, works fine in game, throws an error in the editor.

**Comment by Nico314159** [comment] 2024-07-09 15:13
You're supposed to remove the `I;` part.

**Comment by MulverineX** [comment] 2024-07-09 17:07
Duplicate of #1471

**Closed** 2024-07-09 17:08 UTC
Labels: *duplicate
