### ISSUE TITLE
Suggestion: "Cannot find XXX" create file shortcut

### ISSUE THREAD

**Issue by RoarkCats** [SpyglassMC/Spyglass#1611] opened 2024-10-07 09:39 UTC
It would be useful if you could control-click (or other access method) on a tag or function or other datapack file even if it said "cannot find" and it would create that file fresh for you to edit (assuming it really wasn't already made)

this way as you're writing the pack, you could write a function call or tag ref or whatever and directly go into the function/tag/etc without having to go to the sidebar and create the file

this would be especially useful in large projects where scrolling through all the files to find where you want to create the new file can be a minor hassle

**Comment by misode** [comment] 2024-10-07 14:40
Duplicate of #1222

**Closed by misode** 2024-10-07 14:40 UTC
