### ISSUE TITLE
nbt display errors

### ISSUE THREAD

**Issue by Rain-Blueberry** [SpyglassMC/Spyglass#1051] opened 2023-05-12 08:09 UTC
In Version 3.4.11
![photo1](https://github.com/SpyglassMC/Spyglass/assets/133335879/ebc59d9e-6eb3-46f0-b3c4-1526493bf129)
execute as @a[nbt={Inventory:[{Slot:103b,id:"minecraft:netherite_helmet"}]}] run tp @s ~ ~ ~
execute as @a[nbt={Inventory:[{Slot:103b,id:"minecraft:netherite_helmet"}]}] run tag @s add test
display errors
![photo2](https://github.com/SpyglassMC/Spyglass/assets/133335879/971a932a-e31c-42c5-b311-227ea867f06d)
![photo3](https://github.com/SpyglassMC/Spyglass/assets/133335879/a709c7f2-958b-4489-ad99-4774da040a21)
In game display true

**Comment by SPGoding** [comment] 2023-05-12 09:00
What is the error message in VS Code? I couldn't seem to reproduce this issue.

**Comment by Rain-Blueberry** [comment] 2023-05-12 09:06
> What is the error message in VS Code? I couldn't seem to reproduce this issue.
![photo1](https://github.com/SpyglassMC/Spyglass/assets/133335879/e1da4fcd-49f5-4bb1-bca8-64a25807dfd5)
Expected a space to seperate two arguments.

**Comment by Rain-Blueberry** [comment] 2023-05-12 09:19
> What is the error message in VS Code? I couldn't seem to reproduce this issue.

And Version 3.4.9 don't have this error

**Comment by SPGoding** [comment] 2023-05-12 10:06
Does version 3.4.12 also have this issue?

**Comment by Rain-Blueberry** [comment] 2023-05-12 11:09
> Does version 3.4.12 also have this issue?

Version 3.4.12 also have this issue.
![photo2](https://github.com/SpyglassMC/Spyglass/assets/133335879/b70896c5-ef6a-4b6a-8497-b827e79a1361)

**Comment by Rain-Blueberry** [comment] 2023-05-12 11:24
> Does version 3.4.12 also have this issue?

Besides this, there is another issue
![photo](https://github.com/SpyglassMC/Spyglass/assets/133335879/5dccf842-2f92-4b7d-a737-95c4ead19432)
These two issues are not present in Version 3.4.9

**Comment by Nyali-ce** [comment] 2023-05-12 20:08
I'm on 3.2.0 and I get this issue too, as soon as you add a nbt selector, its displayed as an error
![image](https://github.com/SpyglassMC/Spyglass/assets/51309139/6126f4f9-6ec2-4c4f-8ddf-7f06681efa66)

**Comment by SPGoding** [comment] 2023-05-13 03:49
Could anyone affected by this bug please try installing these two different builds of the extension in VS Code (go to sidebar -> Extensions -> three dots -> Install from VSIX...) and see if the issue is still there in either debug version?

[debug-vsix.zip](https://github.com/SpyglassMC/Spyglass/files/11468803/debug-vsix.zip)

**Comment by Rain-Blueberry** [comment] 2023-05-13 06:06
> Could anyone affected by this bug please try installing these two different builds of the extension in VS Code (go to sidebar -> Extensions -> three dots -> Install from VSIX...) and see if the issue is still there in either debug version?
> 
> [debug-vsix.zip](https://github.com/SpyglassMC/Spyglass/files/11468803/debug-vsix.zip)

These two versions still have this issue
![photo4](https://github.com/SpyglassMC/Spyglass/assets/133335879/79483731-5359-4fb9-b088-832eaaf4571b)
![photo5](https://github.com/SpyglassMC/Spyglass/assets/133335879/39c8e834-675b-48a0-afac-8f543d582b62)

**Comment by SPGoding** [comment] 2023-05-13 23:08
Thank you so much for testing! Is this still an issue in 3.4.13?

**Comment by Rain-Blueberry** [comment] 2023-05-14 00:26
> Thank you so much for testing! Is this still an issue in 3.4.13?

Version 3.4.13 don't have this issue ,but have another issue
![photo](https://github.com/SpyglassMC/Spyglass/assets/133335879/e37bcfc0-9b16-4c74-b9c1-5c76a06c7ec3)
There seems to be something missing from the "minecraft:item"

**Comment by MulverineX** [comment] 2024-04-18 23:49
Will be fixed in v4.

**Closed by MulverineX** 2024-04-18 23:49 UTC
Labels: 💩 v3
