### ISSUE TITLE
Quick fix that makes a file

### ISSUE THREAD

**Issue by Trioplane** [SpyglassMC/Spyglass#1541] opened 2024-07-22 07:09 UTC
![image](https://github.com/user-attachments/assets/921fca63-7d23-4b6c-a0c2-d3dc90ddc1aa)
It would be nice if there was a quick fix that just makes the file in the path provided, maybe it could support .json files too?

**Comment by NeunEinser** [comment] 2024-07-22 07:11
Duplicate of #1222

**Closed by NeunEinser** 2024-07-22 07:11 UTC
Labels: *duplicate
