### ISSUE TITLE
The Spyglass Language Server is't work

### ISSUE THREAD

**Issue by Blackblock-inc** [SpyglassMC/Spyglass#1565] opened 2024-08-09 16:58 UTC
I am trying to find a solution to the problem, just like #1466 #931 issues.
My PC is from China and Github may not be accessible, so I tried using VPN and modifying Hosts, but none of these worked.
The version I am using is v4.2.0, while v4.0.0-v4.2.0 will prompt this.
3.4.19 can download datapacks, but spyglass cannot recognize statements.
By the way, I also tried changing it to jsDeliv, which will show that the channel is closed.
ERRORs:
1.  The Spyglass Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2.  Client spyglass Language Server. connection to server is erroring. channel closed.
I don't know what happened, maybe the download server doesn't allow proxy connections, and at the same time, my computer can't directly connect to the download server.

[1-Spyglass Language Server.log](https://github.com/user-attachments/files/16564632/1-Spyglass.Language.Server.log)

**Comment by MulverineX** [comment] 2024-08-09 20:56
Duplicate of #1480

**Closed** 2024-08-09 20:56 UTC
Labels: *duplicate
