### ISSUE TITLE
Go to definition and find references does not work when your cursor is exactly behind the symbol, or when the symbol is highlighted

### ISSUE THREAD

**Issue by NeunEinser** [SpyglassMC/Spyglass#1619] opened 2024-10-13 16:51 UTC
## Steps to reproduce
1. type sth like `function foo:bar`
2. Make sure the function exists
3. Put your cursor where the pipe is this: `function foo:bar|`
4. Press F12
-> ❌ doesn't work
6. double click on the function to highlight everything after the namespace
7. Press F12
-> ❌ doesn't work
8. Put your cursor where the pipe is this: `function foo:ba|r`
-> ✅ does work

## What happened
I get a vscode error "No definition found for bar"

## What I expected
It going to the definition behind my cursor

**Comment by TheAfroOfDoom** [comment] 2024-10-13 21:04
duplicate of https://github.com/SpyglassMC/Spyglass/issues/1526

**Comment by TheAfroOfDoom** [comment] 2024-10-13 21:04
i fixed this on a local branch but it's really hacky and not mergeable

**Closed** 2024-10-13 21:39 UTC
Labels: 🐛 bug, *duplicate
