### ISSUE TITLE
"*" is not recognized as score_holder

### ISSUE THREAD

**Issue by NeunEinser** [SPYGlassMC/SPYGlass#793] opened 2020-12-06 14:59 UTC
"*" as score_holder means *all existing scoreholders*, yet if you use linting rules, it is required to be defined and match your conventions.

![grafik](https://user-images.githubusercontent.com/12124394/101283636-fef88f00-37db-11eb-9970-5a079107bc89.png)

**Comment by ChenCMD** [comment] 2020-12-06 15:01
Duplicate of #781

**Closed by ChenCMD** 2020-12-06 15:01 UTC
