### ISSUE TITLE
Modifying folders not created in the workspace sometimes causes Error: EPERM: operation not permitted

### ISSUE THREAD

**Issue by Dahesor** [SpyglassMC/Spyglass#1490] opened 2024-07-07 21:57 UTC
I started a new data pack, and copied some files and folders from another data pack to this new one. However, when I am trying to rename the copied folders, vs code took a minute and said `Error: EPERM: operation not permitted`.

I disabled all my extensions and it can rename normally again. I then enabled my extensions one by one and test if it can rename, and I learned it is Spyglass causing this problem.

Moving all the contents inside this folder away makes it rename-able again, but if I put them back in then I can no longer rename it.

This never happened on folders that I created in this new data pack.

When I copied the folders from another data pack into this new one, a lot of warning popped out because all the name space paths are incorrect. It might has something to do with this? Or something wrong in the cache?

I also searched on the internet and found the following posts, not sure if they are useful:

[https://stackoverflow.com/questions/58707277/vs-code-error-eperm-operation-not-permitted](https://stackoverflow.com/questions/58707277/vs-code-error-eperm-operation-not-permitted)

[https://github.com/microsoft/vscode/issues/184145](https://github.com/microsoft/vscode/issues/184145)

Thanks

**Comment by misode** [comment] 2024-07-07 22:17
Duplicate of #1414

**Closed by misode** 2024-07-07 22:17 UTC

**Comment by carloswm85** [comment] 2024-08-22 10:15
Here's a workaround to this problem: https://stackoverflow.com/a/78900972/7389293

---

This seems to be a problem related to running MULTIPLE processes inside VSCode,  and with this disallowing the move of folders.

I received this error while running an Angular 17 app and a NodeJS server at the same time, and trying to move one of the project folders:

[![enter image description here][1]][1]

I solved it in Windows 11 by using [File LockSmith][2].

1. Stop all the visible task and processes you may have running:
   
   [![enter image description here][3]][3]

1. And then execute File Locksmith in the projects root folder (in this case, named `_ta-app`).
1. Press `End Task` buttons for all child processes, except for the main VSCode editor one.

   [![enter image description here][4]][4]

1. That should enable moving/renaming folders.

   [![enter image description here][5]][5]

As you can see, it is working now.


  [1]: https://i.sstatic.net/WhZkWWwX.png
  [2]: https://www.google.com/search?q=windows%2011%20file%20locksmith
  [3]: https://i.imgur.com/7HoMfqD.gif
  [4]: https://i.imgur.com/NMWXi7F.gif
  [5]: https://i.imgur.com/37edUrk.gif

**Comment by NuzzGO** [comment] 2025-03-28 19:31
Hi everyone!

I had the same problem on Win 10, when I want to configure my ESP-IDF on VSCode. 
Steps what I did to solve the problem:
-  Open terminal (CMD) as administrator and try to paste:
**npm i -g npm
npm init --yes**

1. After that you should open VSCode ans Administartor (it's important step) and end task by task menager.

2. Go to your folder here you have your VSCode project and delete .vscode (you have to check selected option in explorer: **hidden elements**)

3. Then you can run as admin. VSCode....
You should have something like this on your screen (if you have some terminals, close all):

![Image](https://github.com/user-attachments/assets/8d933d26-f2c5-4bfd-bf8c-7fb08a33f4dd)
 
4. Now you can reboot your computer, open vscode, make sure (again..) you have close all terminals and then you can try install ESP-IDF...

If It's not working you should install the newest version of node.js and choose options with chocolatey in installation wizard.
Then follow the steps on screen but after all you will have notification to reboot and DO IT :) 

after that again do steps with npm in cmd in my env.. or choose powershell.. I have to use cmd maybe you will need specify your path of node.js if still have a problem but It's only my suggestion.. Commands to paste:

**npm cache clean
npm i -g npm
npm init --yes**

I don't know at all why but in my case I had to reboot again and do step 4 and now works fine. 

I know Its a little mess here but I did It on my 3 comupters and witrh my friend and more or less this steps always helps us :) 
Maybe I will help somebody 🦸
