### ISSUE TITLE
Header & inline error/warn prevention

### ISSUE THREAD

**Issue by MulverineX** [SPYGlassMC/SPYGlass#894] opened 2021-07-01 18:22 UTC
eg. `# @no-warn` / `# @no-error` would prevent errors/warnings from reaching the editor/linter/cli in the following line, or the whole file if in the header block.

**Comment by SPGoding** [comment] 2021-07-01 18:23
Duplicate of #486.

**Closed by SPGoding** 2021-07-01 18:23 UTC
Labels: /mcfunction, ✨ feature, 🔷 lint
