### ISSUE TITLE
Removing item components from items in a give command gives an error.

### ISSUE THREAD

**Issue by mageowl** [SpyglassMC/Spyglass#1651] opened 2024-11-23 21:16 UTC
The following code produces an error on pack format 57.
```mcfunction
give @s potato[!food]
```
The same thing happens with `minecraft:food`

**Comment by mageowl** [comment] 2024-11-23 21:16
In VS Code:
![Image](https://github.com/user-attachments/assets/c1782758-c37c-4ea1-85c2-aa81f0168699)

**Comment by misode** [comment] 2024-11-23 21:32
Duplicate of #1496

**Closed** 2024-11-23 21:33 UTC
