### ISSUE TITLE
billboard nbt expects compound tag instead of string tag

### ISSUE THREAD

**Issue by pauloalbert** [SpyglassMC/Spyglass#1030] opened 2023-03-11 16:29 UTC
Version: 3.4.9, set on: Latest snapshot + 1.19.4

When summoning/ modifying a text_display i noticed that `{billboard:"fixed"}` is erroneously highlighted as a warning:
`Expected a compound tag but got a string tag (rule: “nbtTypeCheck”).`
The autocomplete also labels billboard as Type: Or

However, as is the case in the game and in the [wiki](https://minecraft.fandom.com/wiki/Display),
billboard should accept only "fixed" "horizontal" "vertical" and "center" as parameters

**Comment by SPGoding** [comment] 2023-05-12 07:19
Duplicate of Yurihaia/mc-nbtdoc#47

**Closed by SPGoding** 2023-05-12 07:19 UTC
Labels: 💩 v3
