### ISSUE TITLE
Invalid command in text component "suggest_command" is treated as error

### ISSUE THREAD

**Issue by TheMuffinPony** [SpyglassMC/Spyglass#1682] opened 2024-12-25 22:53 UTC
Hello!  I want to make a JSON text component that allows the player to click on it and enter a number as a `/trigger` command.  Spyglass treats the command inside as a command, and emits an error because it is invalid.

## Minimally reproducible example
Put the following in a `.mcfunction` file:
```
tellraw @s [{"text":"Click here to enter the passcode","clickEvent": {"action": "suggest_command","value":"/trigger passcode set "}}]
```
What happened: Spyglass says that the suggested command is an error and marks the file as having an error (red name) in VS Code.  While the command does not work on its own, it is intended for the player to enter the passcode before submitting the command.

What I want to happen: Either Spyglass ignores the error or gives me an easy override to say "I am expecting the command inside to not work on its own."

**Comment by SPGoding** [comment] 2024-12-26 01:42
Duplicate of #1535.

**Closed by SPGoding** 2024-12-26 01:42 UTC
Labels: *duplicate
