### ISSUE TITLE
Advancement command criterion checking

### ISSUE THREAD

**Issue by tryashtar** [SpyglassMC/Spyglass#1454] opened 2024-07-02 08:05 UTC
```mcfunction
advancement grant @s only adventure/adventuring_time blahblah
kill @s[advancements={adventure/adventuring_time={blahblah=true}}]
```

These commands are invalid because that advancement doesn't contain a criterion called "blahblah"

Spyglass could both suggest and validate these criteria names as found in the advancement definition (and for the selector version, make sure there are no duplicates!)

**Comment by misode** [comment] 2024-07-02 15:13
Duplicate of #883

**Closed by misode** 2024-07-02 15:13 UTC
