### ISSUE TITLE
Server initialization failed

### ISSUE THREAD

**Issue by huimanman** [SpyglassMC/Spyglass#1445] opened 2024-07-02 01:44 UTC
[log.txt](https://github.com/user-attachments/files/16060560/log.txt)

**Comment by misode** [comment] 2024-07-02 01:53
Looking at the crash log, this seems like the same issue that was reported on discord. The language server will crash when there is no workspace folder open. It has already been fixed in #1428

**Closed by misode** 2024-07-02 01:53 UTC
Labels: 🐛 bug, 🚑 crash-freeze

**Comment by huimanman** [comment] 2024-07-02 02:05
connection to server is erroring.
Open in the workspace
[log.txt](https://github.com/user-attachments/files/16060676/log.txt)

**Comment by misode** [comment] 2024-07-02 02:33
This new crash is caused by a certificate chain error when downloading files from github. Is `api.github.com` or `raw.githubusercontent.com` blocked in your country?

Try using a different data source by creating a `spyglass.json` file in the root of the workspace:
```json
{
  "env": {
    "dataSource": "jsDelivr"
  }
}
```

**Comment by huimanman** [comment] 2024-07-02 02:41
Yes, I live in Chinese mainland but the jsDelivr data source doesn't work :(

Is it possible to add Gitee data sources?

**Comment by misode** [comment] 2024-07-02 03:05
You can use a custom URL, with placeholder variables: `${user}`, `${repo}`, `${tag}`, and `${path}`. But I'm not sure what you could use tbh... The repo it's fetching data from is https://github.com/misode/mcmeta/
